/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e4a924c0-e9b9-4656-b002-898b6c6b2f98",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UoayDMe9B",
    "aws_user_pools_web_client_id": "3cc5ufsgdjh7i6cvnala7dl2q2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://uscphmxmdrfv3dzywc4xljmswy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dw53htkdvjh2zbiyhja2xt6gse"
};


export default awsmobile;
